name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main, github-actions ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Read Base Sepolia addresses
        id: addresses
        run: |
          echo "Reading contract addresses from base-sepolia-addresses.json"
          CARD_REGISTRY=$(jq -r '.CARD_REGISTRY' base-sepolia-addresses.json)
          DECK_REGISTRY=$(jq -r '.DECK_REGISTRY' base-sepolia-addresses.json)
          GAME_ENGINE=$(jq -r '.GAME_ENGINE' base-sepolia-addresses.json)
          echo "CARD_REGISTRY=$CARD_REGISTRY" >> $GITHUB_OUTPUT
          echo "DECK_REGISTRY=$DECK_REGISTRY" >> $GITHUB_OUTPUT
          echo "GAME_ENGINE=$GAME_ENGINE" >> $GITHUB_OUTPUT

      - name: Install dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps

      - name: Update contract addresses and configs
        working-directory: frontend
        run: |
          # Copy production config and replace contract addresses
          cp src/lib/web3/config.production.ts src/lib/web3/config.ts
          
          # Replace the placeholder addresses with actual addresses
          sed -i "s/REPLACE_CARD_REGISTRY/${{ steps.addresses.outputs.CARD_REGISTRY }}/g" src/lib/web3/config.ts
          sed -i "s/REPLACE_DECK_REGISTRY/${{ steps.addresses.outputs.DECK_REGISTRY }}/g" src/lib/web3/config.ts
          sed -i "s/REPLACE_GAME_ENGINE/${{ steps.addresses.outputs.GAME_ENGINE }}/g" src/lib/web3/config.ts

      - name: Create .env file
        working-directory: frontend
        run: |
          echo "VITE_PRIVY_APP_ID=${PRIVY_APP_ID:-default-app-id}" > .env
          echo "VITE_CHAIN_ID=84532" >> .env
          echo "VITE_RPC_URL=https://sepolia.base.org" >> .env
          echo "VITE_CARD_REGISTRY_ADDRESS=${{ steps.addresses.outputs.CARD_REGISTRY }}" >> .env
          echo "VITE_DECK_REGISTRY_ADDRESS=${{ steps.addresses.outputs.DECK_REGISTRY }}" >> .env
          echo "VITE_GAME_ENGINE_ADDRESS=${{ steps.addresses.outputs.GAME_ENGINE }}" >> .env
        env:
          PRIVY_APP_ID: ${{ secrets.VITE_PRIVY_APP_ID }}

      - name: Build frontend
        working-directory: frontend
        run: npm run build
        env:
          CI: true
          GITHUB_ACTIONS: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4